# AUTOSTART
# most apps are either started as systemd service like either directly like hyprpolkitagent or indirectly via uwsm
# and ~/.config/autostart
exec-once = uwsm app -- nm-applet --indicator
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = uwsm app -- nwg-screenshot-applet
exec-once = uwsm app -- hyprpanel
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
