[general]
import = [
"/home/mpuchstein/.config/alacritty/themes/themes/github_dark.toml"
]
live_config_reload = true
ipc_socket = true

[window]
opacity = 0.7

[font]
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }
size = 9

[mouse]
hide_when_typing = true
